title: Sean Moran
description: Personal Page
long_description: Executive Director at JP Morgan Chase & Co.
show_downloads: false
google_analytics: UA-17169879-4
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
